### ISSUE TITLE
线程池限制下的错误解决方案RejectedExecutionException

### ISSUE THREAD

**Issue by jemygraw** [qiniu/qiniu-logging-plugin#11]
```
Exception in thread "Thread-1" java.util.concurrent.RejectedExecutionException: Task com.qiniu.appender.QiniuLoggingGuard$3@5c499319 rejected from java.util.concurrent.ThreadPoolExecutor@4f352d43[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at com.qiniu.appender.QiniuLoggingGuard.pushLogs(QiniuLoggingGuard.java:100)
	at com.qiniu.appender.QiniuLoggingGuard.access$100(QiniuLoggingGuard.java:15)
	at com.qiniu.appender.QiniuLoggingGuard$2.run(QiniuLoggingGuard.java:58)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jemygraw** [comment]
push采用cached pool，超过了直接抛exception，加入retry。
retry采用fixed pool，慢慢传。

**Comment by jemygraw** [comment]
fixed in 
6d8d631185087d85b85cabffa7b02caa3e42b109
612b8dbd3dc4097ad629da4e3ac721a35f1ca091
e3dfbd2948e1678e7bd4bb4681f213ab7a415fdc
