### ISSUE TITLE
ElasticSearch6.2.1 ElasticsearchUncaughtExceptionHandler

### ISSUE THREAD

**Issue by jemygraw** [qiniu/qiniu-logging-plugin#15]
```
[2018-07-06T18:03:58,263][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [Thread-3]
java.security.AccessControlException: access denied ("java.io.FilePermission" "/Users/jemy/Temp/logging" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_172]
	at java.io.File.exists(File.java:814) ~[?:1.8.0_172]
	at com.qiniu.appender.QiniuLoggingGuard.pushLogs(QiniuLoggingGuard.java:66) ~[qiniu-logging-plugin-log4j2-1.0.0.jar:?]
	at com.qiniu.appender.QiniuLoggingGuard.access$100(QiniuLoggingGuard.java:15) ~[qiniu-logging-plugin-log4j2-1.0.0.jar:?]
	at com.qiniu.appender.QiniuLoggingGuard$2.run(QiniuLoggingGuard.java:58) ~[qiniu-logging-plugin-log4j2-1.0.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[2018-07-06T18:03:58,308][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [pool-2-thread-12]
java.security.AccessControlException: access denied ("java.net.SocketPermission" "115.231.182.53:443" "connect,resolve")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkConnect(SecurityManager.java:1051) ~[?:1.8.0_172]
	at java.net.Socket.connect(Socket.java:584) ~[?:1.8.0_172]
	at okhttp3.internal.Platform.connectSocket(Platform.java:121) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:185) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:170) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296) ~[okhttp-3.3.1.jar:?]
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) ~[okhttp-3.3.1.jar:?]
	at okhttp3.RealCall.getResponse(RealCall.java:243) ~[okhttp-3.3.1.jar:?]
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201) ~[okhttp-3.3.1.jar:?]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163) ~[okhttp-3.3.1.jar:?]
	at okhttp3.RealCall.execute(RealCall.java:57) ~[okhttp-3.3.1.jar:?]
	at com.qiniu.pandora.http.Client.send(Client.java:365) ~[qiniu-pandora-sdk-2.0.2.jar:?]
	at com.qiniu.pandora.http.Client.post(Client.java:344) ~[qiniu-pandora-sdk-2.0.2.jar:?]
	at com.qiniu.pandora.http.Client.post(Client.java:327) ~[qiniu-pandora-sdk-2.0.2.jar:?]
	at com.qiniu.pandora.common.PandoraClientImpl.post(PandoraClientImpl.java:51) ~[qiniu-pandora-sdk-2.0.2.jar:?]
	at com.qiniu.pandora.pipeline.sender.DataSender.send(DataSender.java:64) ~[qiniu-pandora-sdk-2.0.2.jar:?]
	at com.qiniu.appender.Log4j2QiniuAppender$2.run(Log4j2QiniuAppender.java:150) ~[qiniu-logging-plugin-log4j2-1.0.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by jemygraw** [comment]
这种情况是因为Java的Security Policy导致的。在elasticsearch6.2.1的config目录下面，新建一个文件叫做 qiniu-plugin.policy, 里面加入如下内容：

```

```

然后在config/jvm.options 最后加上：

```
# security manager
-Djava.security.policy=/Users/jemy/Developer/BigData/elasticsearch-6.2.1/config/qiniu-plugin.policy
```

注意这里使用全路径。

然后使用 bin/elasticsearch 启动，观察输出：

```
[2018-07-07T09:59:06,754][INFO ][o.e.n.Node               ] [tiger] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/var/folders/ky/w_l4krjj4vsf0731p_2_2m700000gp/T/elasticsearch.gIxRVJ9D, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Djava.security.policy=/Users/jemy/Developer/BigData/elasticsearch-6.2.1/config/qiniu-plugin.policy, -Des.path.home=/Users/jemy/Developer/BigData/elasticsearch-6.2.1, -Des.path.conf=/Users/jemy/Developer/BigData/elasticsearch-6.2.1/config]
```

其中有 -Djava.security.policy 字样的就表示生效了。
