### ISSUE TITLE
logback plugin在spring项目中测试出现如下exception

### ISSUE THREAD

**Issue by jemygraw** [qiniu/qiniu-logging-plugin#5]
```
com.qiniu.pandora.common.QiniuException: http://pipeline-pdex.qiniu.io/v2/workflows/springboot/start  
{ResponseInfo:com.qiniu.pandora.http.Response@29e495ff,status:400, reqId:A3kUCsg5VW88W5w_, xlog:STREAMING:105/400;PANDORA-STREAMING:106/400, xvia:, adress:pipeline-pdex.qiniu.io/10.20.43.36:80, duration:0.000000 s, error:E18644: Start workflow failed: illegal to start workflow in status: Starting}  
{"error":"E18644: Start workflow failed: illegal to start workflow in status: Starting"}
	at com.qiniu.pandora.http.Client.send(Client.java:371)
	at com.qiniu.pandora.http.Client.post(Client.java:344)
	at com.qiniu.pandora.http.Client.post(Client.java:327)
	at com.qiniu.pandora.common.PandoraClientImpl.post(PandoraClientImpl.java:51)
	at com.qiniu.pandora.pipeline.PipelineClient.startWorkflow(PipelineClient.java:109)
	at com.qiniu.appender.QiniuAppenderClient.createAppenderWorkflow(QiniuAppenderClient.java:118)
	at com.qiniu.appender.LogbackQiniuAppender.start(LogbackQiniuAppender.java:200)
	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:177)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:149)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.reinitialize(LogbackLoggingSystem.java:212)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:75)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:264)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:237)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:200)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:173)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at com.example.demo.DemoApplication.main(DemoApplication.java:10)
```

**Comment by jemygraw** [comment]
这个问题是启动workflow之前检测的条件不严谨，因为workflow创建之后，就立即启动中了，不需要再Start。所以增加对Starting状态的检测。

**Comment by jemygraw** [comment]
fixed in 238fa4158245df4e383e8750bcaa5dbfb4da10f7
